using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Constructors
{
    class Program
    {
        static void Main()
        {
            // what the constructors do is, when an instance of a class is created the constructors fills the 
            // default values that its attributes will take. If the class has no constrctors, a constructor is
            // generated by default which assign the default values to all class attributes (null, 0 or false)

            // class with custom constructors. since we have written constructors ourselves, when the class
            // is instantiated we need to provide parameters to initialise the class depending on the constructor
            // we will use
            Customer customer = new Customer();
            Customer newCustomer1 = new Customer("Aris"); // uses the constructor which takes string as the only parameter
            Customer newCustomer2 = new Customer("Aris", 32); // uses the constructor which takes both string and in
        }
    }
}
